"""
AeroLens AI - Backend Data Models & Telemetry Data Store
Provides structured data for hotspots, forecasts, explainable AI (XAI), alerts, and locations.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime, timezone

SYSTEM_STATUS = {
    "satelliteCoverage": {
        "label": "Satellite Coverage",
        "value": "94%",
        "status": "Nominal",
        "detail": "Sentinel-5P TROPOMI (ESA) + MODIS Aqua/Terra (NASA) daily pass processed.",
        "lastSync": "18:30 IST",
        "qualityScore": 94.2
    },
    "groundStations": {
        "label": "Ground Stations Available",
        "value": "82%",
        "status": "Active",
        "detail": "344 of 420 CPCB CAAQMS stations streaming 15-minute continuous telemetry.",
        "lastSync": "Live (2 mins ago)",
        "qualityScore": 82.0
    },
    "weatherData": {
        "label": "Weather Assimilation",
        "value": "Available",
        "status": "Optimal",
        "detail": "ECMWF ERA5 + IMD high-resolution numerical weather prediction assimilation.",
        "lastSync": "Hourly sync (22:00 IST)",
        "qualityScore": 98.5
    },
    "modelConfidence": {
        "label": "Model Confidence",
        "value": "High (91.4%)",
        "status": "High Confidence",
        "detail": "Ensemble cross-validation score based on 16 Spatial ConvLSTM runs.",
        "lastSync": "Inference cycle #1042",
        "qualityScore": 91.4
    },
    "overallStatus": "Monitoring Active",
    "activeHotspotsCount": 12,
    "hotspotChange": "+3 in last 6h",
    "pollutionEventsCount": 3,
    "predictedNationalAqi": 287,
    "predictedNationalStatus": "Poor",
    "forecastTrend": "Deteriorating"
}

HOTSPOTS_DATABASE: List[Dict[str, Any]] = [
    {
        "id": "hs-delhi-ncr",
        "name": "Delhi NCR (Anand Vihar - Jahangirpuri Belt)",
        "shortName": "Delhi NCR",
        "state": "National Capital Region",
        "lat": 28.6139,
        "lng": 77.2090,
        "severity": "Severe",
        "currentAqi": 287,
        "predictedAqi": 342,
        "aqiCategory": "Poor",
        "predictedCategory": "Very Poor",
        "hchoLevel": 26.8,
        "hchoBaseline": 9.4,
        "hchoAnomalyRatio": "+185%",
        "no2Level": 78.4,
        "pm25": 168.2,
        "pm10": 294.0,
        "aerosolIndex": 2.84,
        "temperature": 31.4,
        "humidity": 68,
        "windSpeed": 3.2,
        "windDirection": "NW",
        "pblHeight": 420,
        "confidence": 94.2,
        "detectionTime": "2026-08-20 22:30 IST",
        "primarySource": "Industrial Solvents & Stagnant Dense Traffic Precursors",
        "statusBadge": "HIGH-SEVERITY ANOMALY DETECTED",
        "actionStatus": "Alert Dispatched",
        "advisory": "Atmospheric boundary layer compression is preventing formaldehyde and NO2 dispersion. Sensitive groups should avoid outdoor exertion.",
        "satPassTime": "Sentinel-5P Orbit #38492 at 13:42 IST",
    },
    {
        "id": "hs-ludhiana",
        "name": "Ludhiana - Khanna Industrial Corridor",
        "shortName": "Ludhiana Corridor",
        "state": "Punjab",
        "lat": 30.9010,
        "lng": 75.8573,
        "severity": "Severe",
        "currentAqi": 264,
        "predictedAqi": 318,
        "aqiCategory": "Poor",
        "predictedCategory": "Very Poor",
        "hchoLevel": 24.2,
        "hchoBaseline": 8.8,
        "hchoAnomalyRatio": "+175%",
        "no2Level": 62.1,
        "pm25": 145.0,
        "pm10": 252.0,
        "aerosolIndex": 3.12,
        "temperature": 33.1,
        "humidity": 59,
        "windSpeed": 4.1,
        "windDirection": "WNW",
        "pblHeight": 510,
        "confidence": 91.8,
        "detectionTime": "2026-08-20 21:15 IST",
        "primarySource": "Textile Dyeing Volatiles & Agro-Biomass Pyrolysis Precursors",
        "statusBadge": "HIGH-SEVERITY ANOMALY DETECTED",
        "actionStatus": "Active Anomaly",
        "advisory": "Unusually high tropospheric HCHO column detected coinciding with thermal hotspots. Early alert triggered for regional SPCB enforcement.",
        "satPassTime": "Sentinel-5P Orbit #38492 at 13:41 IST",
    },
    {
        "id": "hs-kanpur",
        "name": "Kanpur - Unnao Industrial Cluster",
        "shortName": "Kanpur Belt",
        "state": "Uttar Pradesh",
        "lat": 26.4499,
        "lng": 80.3319,
        "severity": "High",
        "currentAqi": 238,
        "predictedAqi": 279,
        "aqiCategory": "Poor",
        "predictedCategory": "Poor",
        "hchoLevel": 19.4,
        "hchoBaseline": 9.1,
        "hchoAnomalyRatio": "+113%",
        "no2Level": 58.7,
        "pm25": 128.5,
        "pm10": 215.0,
        "aerosolIndex": 2.15,
        "temperature": 32.8,
        "humidity": 72,
        "windSpeed": 5.4,
        "windDirection": "ENE",
        "pblHeight": 580,
        "confidence": 89.5,
        "detectionTime": "2026-08-20 20:45 IST",
        "primarySource": "Chemical Tanning & Secondary Aerosol Precursors",
        "statusBadge": "ELEVATED ANOMALY WATCH",
        "actionStatus": "Monitoring Active",
        "advisory": "HCHO levels exceeding seasonal threshold by 113%. Calm wind regime favoring localized volatile organic compound accumulation.",
        "satPassTime": "Sentinel-5P Orbit #38493 at 14:02 IST",
    },
    {
        "id": "hs-mumbai",
        "name": "Mumbai MMR (Chembur - Mahul Petrochem Zone)",
        "shortName": "Mumbai MMR",
        "state": "Maharashtra",
        "lat": 19.0760,
        "lng": 72.8777,
        "severity": "Moderate",
        "currentAqi": 158,
        "predictedAqi": 182,
        "aqiCategory": "Moderate",
        "predictedCategory": "Moderate",
        "hchoLevel": 14.8,
        "hchoBaseline": 9.6,
        "hchoAnomalyRatio": "+54%",
        "no2Level": 51.2,
        "pm25": 68.4,
        "pm10": 132.0,
        "aerosolIndex": 1.45,
        "temperature": 29.5,
        "humidity": 84,
        "windSpeed": 12.8,
        "windDirection": "SW",
        "pblHeight": 750,
        "confidence": 88.0,
        "detectionTime": "2026-08-20 22:00 IST",
        "primarySource": "Petrochemical Refining & Coastal Marine Emissions",
        "statusBadge": "MODERATE FLUX DETECTED",
        "actionStatus": "Normal Monitoring",
        "advisory": "Sea breeze provides partial ventilation, dampening severe ground concentration spikes despite moderate HCHO flare detected by TROPOMI.",
        "satPassTime": "Sentinel-5P Orbit #38491 at 13:24 IST",
    },
    {
        "id": "hs-singrauli",
        "name": "Singrauli - Sonbhadra Energy Corridor",
        "shortName": "Singrauli Belt",
        "state": "Madhya Pradesh / UP",
        "lat": 24.1997,
        "lng": 82.6644,
        "severity": "High",
        "currentAqi": 245,
        "predictedAqi": 288,
        "aqiCategory": "Poor",
        "predictedCategory": "Poor",
        "hchoLevel": 21.3,
        "hchoBaseline": 10.2,
        "hchoAnomalyRatio": "+108%",
        "no2Level": 74.3,
        "pm25": 138.0,
        "pm10": 240.0,
        "aerosolIndex": 2.65,
        "temperature": 30.2,
        "humidity": 64,
        "windSpeed": 4.8,
        "windDirection": "SE",
        "pblHeight": 620,
        "confidence": 93.1,
        "detectionTime": "2026-08-20 19:30 IST",
        "primarySource": "Coal Thermal Superclusters & Open Cast Coal Mines",
        "statusBadge": "ELEVATED ANOMALY WATCH",
        "actionStatus": "Alert Dispatched",
        "advisory": "Co-emission of NO2 and formaldehyde detected downwind of thermal power stations. Model forecasts elevated ozone formation.",
        "satPassTime": "Sentinel-5P Orbit #38493 at 14:04 IST",
    },
    {
        "id": "hs-korba",
        "name": "Korba Industrial & Mining Complex",
        "shortName": "Korba Basin",
        "state": "Chhattisgarh",
        "lat": 22.3595,
        "lng": 82.7501,
        "severity": "High",
        "currentAqi": 224,
        "predictedAqi": 260,
        "aqiCategory": "Poor",
        "predictedCategory": "Poor",
        "hchoLevel": 18.9,
        "hchoBaseline": 9.8,
        "hchoAnomalyRatio": "+92%",
        "no2Level": 66.4,
        "pm25": 118.0,
        "pm10": 210.0,
        "aerosolIndex": 2.30,
        "temperature": 30.8,
        "humidity": 70,
        "windSpeed": 6.0,
        "windDirection": "E",
        "pblHeight": 690,
        "confidence": 90.4,
        "detectionTime": "2026-08-20 18:50 IST",
        "primarySource": "Aluminium Smelting & Thermal Combustion",
        "statusBadge": "ELEVATED ANOMALY WATCH",
        "actionStatus": "Monitoring Active",
        "advisory": "Dense industrial emissions trapped by terrain topography during evening cooling cycle.",
        "satPassTime": "Sentinel-5P Orbit #38493 at 14:06 IST",
    },
    {
        "id": "hs-kolkata",
        "name": "Greater Kolkata (Howrah - Dankuni Sector)",
        "shortName": "Kolkata Metro",
        "state": "West Bengal",
        "lat": 22.5726,
        "lng": 88.3639,
        "severity": "Moderate",
        "currentAqi": 172,
        "predictedAqi": 205,
        "aqiCategory": "Moderate",
        "predictedCategory": "Poor",
        "hchoLevel": 15.2,
        "hchoBaseline": 10.1,
        "hchoAnomalyRatio": "+50%",
        "no2Level": 52.8,
        "pm25": 82.0,
        "pm10": 156.0,
        "aerosolIndex": 1.82,
        "temperature": 31.0,
        "humidity": 86,
        "windSpeed": 8.2,
        "windDirection": "S",
        "pblHeight": 710,
        "confidence": 87.2,
        "detectionTime": "2026-08-20 21:00 IST",
        "primarySource": "Foundry Emissions & River Freight Logistics",
        "statusBadge": "MODERATE WATCH",
        "actionStatus": "Normal Monitoring",
        "advisory": "High humidity is promoting secondary particulate formation. Model indicates night-time AQI degradation.",
        "satPassTime": "Sentinel-5P Orbit #38494 at 14:22 IST",
    },
    {
        "id": "hs-patna",
        "name": "Patna - Hajipur Indo-Gangetic Basin",
        "shortName": "Patna Basin",
        "state": "Bihar",
        "lat": 25.5941,
        "lng": 85.1376,
        "severity": "Severe",
        "currentAqi": 272,
        "predictedAqi": 325,
        "aqiCategory": "Poor",
        "predictedCategory": "Very Poor",
        "hchoLevel": 23.9,
        "hchoBaseline": 9.2,
        "hchoAnomalyRatio": "+160%",
        "no2Level": 61.5,
        "pm25": 156.0,
        "pm10": 278.0,
        "aerosolIndex": 2.95,
        "temperature": 32.2,
        "humidity": 76,
        "windSpeed": 3.8,
        "windDirection": "ESE",
        "pblHeight": 480,
        "confidence": 93.6,
        "detectionTime": "2026-08-20 22:10 IST",
        "primarySource": "Brick Kiln Corridors & Stagnant Basin Transboundary Inflow",
        "statusBadge": "HIGH-SEVERITY ANOMALY DETECTED",
        "actionStatus": "Alert Dispatched",
        "advisory": "Valleys along the Ganges basin experiencing thermal inversion trapping volatile formaldehyde plumes.",
        "satPassTime": "Sentinel-5P Orbit #38494 at 14:20 IST",
    },
    {
        "id": "hs-bengaluru",
        "name": "Bengaluru (Peenya Industrial Estate)",
        "shortName": "Bengaluru Tech/Peenya",
        "state": "Karnataka",
        "lat": 12.9716,
        "lng": 77.5946,
        "severity": "Normal",
        "currentAqi": 68,
        "predictedAqi": 74,
        "aqiCategory": "Satisfactory",
        "predictedCategory": "Satisfactory",
        "hchoLevel": 8.6,
        "hchoBaseline": 8.1,
        "hchoAnomalyRatio": "+6%",
        "no2Level": 28.4,
        "pm25": 24.5,
        "pm10": 56.0,
        "aerosolIndex": 0.65,
        "temperature": 24.6,
        "humidity": 62,
        "windSpeed": 14.5,
        "windDirection": "WSW",
        "pblHeight": 1100,
        "confidence": 95.0,
        "detectionTime": "2026-08-20 22:30 IST",
        "primarySource": "Standard Urban Background & Light Manufacturing",
        "statusBadge": "BASELINE NORMAL",
        "actionStatus": "Normal Monitoring",
        "advisory": "Strong plateau winds and deep boundary layer ensure healthy dispersion. Satellite metrics match historical baseline.",
        "satPassTime": "Sentinel-5P Orbit #38491 at 13:20 IST",
    },
    {
        "id": "hs-chennai",
        "name": "Chennai (Manali Petrochemical Corridor)",
        "shortName": "Chennai Manali",
        "state": "Tamil Nadu",
        "lat": 13.0827,
        "lng": 80.2707,
        "severity": "Moderate",
        "currentAqi": 112,
        "predictedAqi": 126,
        "aqiCategory": "Moderate",
        "predictedCategory": "Moderate",
        "hchoLevel": 13.7,
        "hchoBaseline": 9.3,
        "hchoAnomalyRatio": "+47%",
        "no2Level": 39.2,
        "pm25": 42.0,
        "pm10": 92.0,
        "aerosolIndex": 1.10,
        "temperature": 30.5,
        "humidity": 78,
        "windSpeed": 11.2,
        "windDirection": "SE",
        "pblHeight": 890,
        "confidence": 90.8,
        "detectionTime": "2026-08-20 20:10 IST",
        "primarySource": "Fertilizer Plants & Refinery Complexes",
        "statusBadge": "MODERATE WATCH",
        "actionStatus": "Normal Monitoring",
        "advisory": "Moderate formaldehyde elevation localized strictly to the northern industrial harbor corridor.",
        "satPassTime": "Sentinel-5P Orbit #38492 at 13:38 IST",
    },
    {
        "id": "hs-ahmedabad",
        "name": "Ahmedabad - Vatva Chemical Cluster",
        "shortName": "Ahmedabad Vatva",
        "state": "Gujarat",
        "lat": 23.0225,
        "lng": 72.5714,
        "severity": "High",
        "currentAqi": 215,
        "predictedAqi": 248,
        "aqiCategory": "Poor",
        "predictedCategory": "Poor",
        "hchoLevel": 19.8,
        "hchoBaseline": 9.5,
        "hchoAnomalyRatio": "+108%",
        "no2Level": 56.4,
        "pm25": 110.0,
        "pm10": 198.0,
        "aerosolIndex": 2.10,
        "temperature": 34.0,
        "humidity": 52,
        "windSpeed": 7.2,
        "windDirection": "SW",
        "pblHeight": 650,
        "confidence": 92.0,
        "detectionTime": "2026-08-20 19:45 IST",
        "primarySource": "Dyes, Intermediates & Industrial VOC Release",
        "statusBadge": "ELEVATED ANOMALY WATCH",
        "actionStatus": "Monitoring Active",
        "advisory": "Elevated daytime photochemical activity accelerating HCHO oxidation from organic solvent vapors.",
        "satPassTime": "Sentinel-5P Orbit #38491 at 13:28 IST",
    },
    {
        "id": "hs-hyderabad",
        "name": "Hyderabad (Bollaram - Jeedimetla Pharma Zone)",
        "shortName": "Hyderabad Pharma Belt",
        "state": "Telangana",
        "lat": 17.3850,
        "lng": 78.4867,
        "severity": "Moderate",
        "currentAqi": 134,
        "predictedAqi": 148,
        "aqiCategory": "Moderate",
        "predictedCategory": "Moderate",
        "hchoLevel": 14.1,
        "hchoBaseline": 9.0,
        "hchoAnomalyRatio": "+56%",
        "no2Level": 41.8,
        "pm25": 54.0,
        "pm10": 118.0,
        "aerosolIndex": 1.25,
        "temperature": 28.2,
        "humidity": 65,
        "windSpeed": 9.8,
        "windDirection": "WSW",
        "pblHeight": 820,
        "confidence": 89.2,
        "detectionTime": "2026-08-20 21:40 IST",
        "primarySource": "Bulk Drug Synthesis & Organic Solvent Stripping",
        "statusBadge": "MODERATE WATCH",
        "actionStatus": "Normal Monitoring",
        "advisory": "Periodic VOC spikes detected during night batch processes. Dispersion remains adequate.",
        "satPassTime": "Sentinel-5P Orbit #38492 at 13:35 IST",
    }
]

HOURLY_FORECAST_DATA: List[Dict[str, Any]] = [
    {"time": "11:00", "timestamp": "11:00 AM", "aqi": 215, "aqiLower": 210, "aqiUpper": 220, "pm25": 112, "pm10": 210, "hcho": 16.2, "no2": 52, "windSpeed": 7.5, "pblHeight": 950, "isForecast": False},
    {"time": "12:00", "timestamp": "12:00 PM", "aqi": 228, "aqiLower": 222, "aqiUpper": 234, "pm25": 120, "pm10": 225, "hcho": 18.5, "no2": 55, "windSpeed": 7.0, "pblHeight": 1020, "isForecast": False},
    {"time": "13:00", "timestamp": "01:00 PM", "aqi": 242, "aqiLower": 236, "aqiUpper": 248, "pm25": 132, "pm10": 240, "hcho": 21.0, "no2": 58, "windSpeed": 6.2, "pblHeight": 1050, "isForecast": False},
    {"time": "14:00", "timestamp": "02:00 PM", "aqi": 255, "aqiLower": 248, "aqiUpper": 262, "pm25": 144, "pm10": 258, "hcho": 24.1, "no2": 64, "windSpeed": 5.8, "pblHeight": 980, "isForecast": False},
    {"time": "15:00", "timestamp": "03:00 PM", "aqi": 264, "aqiLower": 258, "aqiUpper": 270, "pm25": 152, "pm10": 270, "hcho": 25.4, "no2": 68, "windSpeed": 5.1, "pblHeight": 890, "isForecast": False},
    {"time": "16:00", "timestamp": "04:00 PM", "aqi": 270, "aqiLower": 263, "aqiUpper": 277, "pm25": 158, "pm10": 278, "hcho": 26.0, "no2": 71, "windSpeed": 4.5, "pblHeight": 780, "isForecast": False},
    {"time": "17:00", "timestamp": "05:00 PM", "aqi": 276, "aqiLower": 270, "aqiUpper": 282, "pm25": 161, "pm10": 284, "hcho": 26.2, "no2": 73, "windSpeed": 4.2, "pblHeight": 650, "isForecast": False},
    {"time": "18:00", "timestamp": "06:00 PM", "aqi": 280, "aqiLower": 274, "aqiUpper": 286, "pm25": 164, "pm10": 288, "hcho": 26.5, "no2": 75, "windSpeed": 3.8, "pblHeight": 560, "isForecast": False},
    {"time": "19:00", "timestamp": "07:00 PM", "aqi": 283, "aqiLower": 277, "aqiUpper": 289, "pm25": 166, "pm10": 290, "hcho": 26.7, "no2": 76, "windSpeed": 3.5, "pblHeight": 490, "isForecast": False},
    {"time": "20:00", "timestamp": "08:00 PM", "aqi": 285, "aqiLower": 279, "aqiUpper": 291, "pm25": 167, "pm10": 292, "hcho": 26.8, "no2": 77, "windSpeed": 3.4, "pblHeight": 450, "isForecast": False},
    {"time": "21:00", "timestamp": "09:00 PM", "aqi": 286, "aqiLower": 280, "aqiUpper": 292, "pm25": 168, "pm10": 293, "hcho": 26.8, "no2": 78, "windSpeed": 3.3, "pblHeight": 430, "isForecast": False},
    {"time": "22:00", "timestamp": "10:00 PM", "aqi": 287, "aqiLower": 281, "aqiUpper": 293, "pm25": 168, "pm10": 294, "hcho": 26.8, "no2": 78, "windSpeed": 3.2, "pblHeight": 420, "isForecast": False, "isCurrent": True},
    {"time": "23:00", "timestamp": "11:00 PM (FC)", "aqi": 294, "aqiLower": 284, "aqiUpper": 304, "pm25": 174, "pm10": 302, "hcho": 27.2, "no2": 80, "windSpeed": 2.9, "pblHeight": 390, "isForecast": True},
    {"time": "00:00", "timestamp": "12:00 AM (FC)", "aqi": 306, "aqiLower": 293, "aqiUpper": 319, "pm25": 182, "pm10": 315, "hcho": 27.8, "no2": 82, "windSpeed": 2.6, "pblHeight": 360, "isForecast": True},
    {"time": "01:00", "timestamp": "01:00 AM (FC)", "aqi": 318, "aqiLower": 302, "aqiUpper": 334, "pm25": 190, "pm10": 328, "hcho": 28.3, "no2": 84, "windSpeed": 2.4, "pblHeight": 340, "isForecast": True},
    {"time": "02:00", "timestamp": "02:00 AM (FC)", "aqi": 328, "aqiLower": 310, "aqiUpper": 346, "pm25": 198, "pm10": 338, "hcho": 28.7, "no2": 86, "windSpeed": 2.2, "pblHeight": 320, "isForecast": True},
    {"time": "03:00", "timestamp": "03:00 AM (FC)", "aqi": 336, "aqiLower": 316, "aqiUpper": 356, "pm25": 204, "pm10": 346, "hcho": 29.0, "no2": 88, "windSpeed": 2.1, "pblHeight": 310, "isForecast": True},
    {"time": "04:00", "timestamp": "04:00 AM (FC)", "aqi": 342, "aqiLower": 320, "aqiUpper": 364, "pm25": 208, "pm10": 352, "hcho": 29.2, "no2": 89, "windSpeed": 2.0, "pblHeight": 300, "isForecast": True},
    {"time": "05:00", "timestamp": "05:00 AM (FC)", "aqi": 340, "aqiLower": 318, "aqiUpper": 362, "pm25": 206, "pm10": 350, "hcho": 29.0, "no2": 89, "windSpeed": 2.2, "pblHeight": 310, "isForecast": True},
    {"time": "06:00", "timestamp": "06:00 AM (FC)", "aqi": 335, "aqiLower": 312, "aqiUpper": 358, "pm25": 202, "pm10": 345, "hcho": 28.5, "no2": 87, "windSpeed": 2.6, "pblHeight": 340, "isForecast": True},
    {"time": "07:00", "timestamp": "07:00 AM (FC)", "aqi": 329, "aqiLower": 305, "aqiUpper": 353, "pm25": 196, "pm10": 338, "hcho": 27.9, "no2": 85, "windSpeed": 3.2, "pblHeight": 400, "isForecast": True},
    {"time": "08:00", "timestamp": "08:00 AM (FC)", "aqi": 322, "aqiLower": 298, "aqiUpper": 346, "pm25": 190, "pm10": 330, "hcho": 27.2, "no2": 82, "windSpeed": 4.1, "pblHeight": 480, "isForecast": True},
    {"time": "09:00", "timestamp": "09:00 AM (FC)", "aqi": 312, "aqiLower": 288, "aqiUpper": 336, "pm25": 182, "pm10": 320, "hcho": 26.4, "no2": 78, "windSpeed": 5.0, "pblHeight": 600, "isForecast": True},
    {"time": "10:00", "timestamp": "10:00 AM (FC)", "aqi": 298, "aqiLower": 274, "aqiUpper": 322, "pm25": 172, "pm10": 305, "hcho": 25.1, "no2": 72, "windSpeed": 6.2, "pblHeight": 740, "isForecast": True},
    {"time": "11:00", "timestamp": "11:00 AM (FC)", "aqi": 284, "aqiLower": 258, "aqiUpper": 310, "pm25": 162, "pm10": 290, "hcho": 23.8, "no2": 66, "windSpeed": 7.1, "pblHeight": 880, "isForecast": True},
    {"time": "12:00", "timestamp": "12:00 PM (FC)", "aqi": 272, "aqiLower": 245, "aqiUpper": 299, "pm25": 152, "pm10": 276, "hcho": 22.4, "no2": 60, "windSpeed": 7.8, "pblHeight": 1010, "isForecast": True},
    {"time": "13:00", "timestamp": "01:00 PM (FC)", "aqi": 260, "aqiLower": 232, "aqiUpper": 288, "pm25": 142, "pm10": 262, "hcho": 21.0, "no2": 56, "windSpeed": 8.4, "pblHeight": 1080, "isForecast": True},
    {"time": "14:00", "timestamp": "02:00 PM (FC)", "aqi": 252, "aqiLower": 222, "aqiUpper": 282, "pm25": 136, "pm10": 252, "hcho": 20.1, "no2": 53, "windSpeed": 8.7, "pblHeight": 1090, "isForecast": True},
    {"time": "15:00", "timestamp": "03:00 PM (FC)", "aqi": 246, "aqiLower": 215, "aqiUpper": 277, "pm25": 130, "pm10": 244, "hcho": 19.5, "no2": 51, "windSpeed": 8.5, "pblHeight": 1040, "isForecast": True},
    {"time": "16:00", "timestamp": "04:00 PM (FC)", "aqi": 242, "aqiLower": 210, "aqiUpper": 274, "pm25": 126, "pm10": 238, "hcho": 19.0, "no2": 50, "windSpeed": 8.0, "pblHeight": 960, "isForecast": True},
    {"time": "17:00", "timestamp": "05:00 PM (FC)", "aqi": 244, "aqiLower": 210, "aqiUpper": 278, "pm25": 128, "pm10": 240, "hcho": 19.3, "no2": 52, "windSpeed": 7.2, "pblHeight": 820, "isForecast": True},
    {"time": "18:00", "timestamp": "06:00 PM (FC)", "aqi": 250, "aqiLower": 214, "aqiUpper": 286, "pm25": 134, "pm10": 248, "hcho": 20.2, "no2": 56, "windSpeed": 6.0, "pblHeight": 680, "isForecast": True},
    {"time": "19:00", "timestamp": "07:00 PM (FC)", "aqi": 258, "aqiLower": 220, "aqiUpper": 296, "pm25": 140, "pm10": 258, "hcho": 21.1, "no2": 60, "windSpeed": 5.2, "pblHeight": 550, "isForecast": True},
    {"time": "20:00", "timestamp": "08:00 PM (FC)", "aqi": 266, "aqiLower": 226, "aqiUpper": 306, "pm25": 148, "pm10": 268, "hcho": 22.0, "no2": 64, "windSpeed": 4.5, "pblHeight": 460, "isForecast": True},
    {"time": "21:00", "timestamp": "09:00 PM (FC)", "aqi": 274, "aqiLower": 232, "aqiUpper": 316, "pm25": 154, "pm10": 276, "hcho": 22.8, "no2": 68, "windSpeed": 4.0, "pblHeight": 410, "isForecast": True},
    {"time": "22:00", "timestamp": "10:00 PM (FC)", "aqi": 280, "aqiLower": 236, "aqiUpper": 324, "pm25": 160, "pm10": 284, "hcho": 23.5, "no2": 71, "windSpeed": 3.6, "pblHeight": 380, "isForecast": True},
]

FORECAST_INSIGHT = {
    "headline": "24-Hour Forecast Insight: Atmospheric Compression Ahead",
    "summary": "Air quality is expected to deteriorate from AQI 287 (Poor) to a peak of 342 (Very Poor) over the next 6-8 hours (03:00 - 05:00 AM IST).",
    "primaryDriver": "Calm nocturnal surface winds (< 2.2 km/h) combined with a shallow Planetary Boundary Layer (300m) will trap fresh HCHO and NO₂ precursor emissions near the ground level.",
    "turningPoint": "Gradual recovery forecasted post 10:00 AM tomorrow as solar insolation expands boundary layer depth past 800m.",
    "confidenceLevel": "High (89.6% ensemble agreement across 16 ConvLSTM-XGBoost runs)",
}

CITY_FORECAST_COMPARISON = [
    {"city": "Delhi NCR", "currentAqi": 287, "peakPredictedAqi": 342, "status": "Deteriorating", "color": "#EF4444"},
    {"city": "Ludhiana Corridor", "currentAqi": 264, "peakPredictedAqi": 318, "status": "Deteriorating", "color": "#F97316"},
    {"city": "Patna Basin", "currentAqi": 272, "peakPredictedAqi": 325, "status": "Deteriorating", "color": "#EF4444"},
    {"city": "Kanpur Belt", "currentAqi": 238, "peakPredictedAqi": 279, "status": "Elevated Stagnation", "color": "#F59E0B"},
    {"city": "Mumbai MMR", "currentAqi": 158, "peakPredictedAqi": 182, "status": "Moderate Fluctuations", "color": "#EAB308"},
    {"city": "Bengaluru Tech", "currentAqi": 68, "peakPredictedAqi": 74, "status": "Stable / Good", "color": "#10B981"},
]

XAI_FACTORS = [
    {
        "id": "factor-no2",
        "name": "Tropospheric NO₂ Density",
        "category": "Chemical Precursor",
        "value": "78.4 µg/m³",
        "baseline": "32.0 µg/m³",
        "contribution": 42.5,
        "impactType": "aggravator",
        "percentShare": 29.4,
        "description": "High vehicular & industrial combustion byproduct directly accelerates secondary PM2.5 formation.",
        "color": "#EF4444",
    },
    {
        "id": "factor-hcho",
        "name": "TROPOMI HCHO Anomaly",
        "category": "Satellite Anomaly",
        "value": "26.8 × 10¹⁵ molec/cm²",
        "baseline": "9.4 × 10¹⁵ molec/cm²",
        "contribution": 38.2,
        "impactType": "aggravator",
        "percentShare": 26.5,
        "description": "185% above seasonal baseline, indicating active volatile organic compound oxidation and VOC-limited regime.",
        "color": "#F97316",
    },
    {
        "id": "factor-wind",
        "name": "Wind Stagnation (Low Velocity)",
        "category": "Meteorology",
        "value": "3.2 km/h (Calm)",
        "baseline": "11.5 km/h",
        "contribution": 29.0,
        "impactType": "aggravator",
        "percentShare": 20.1,
        "description": "Severe ventilation deficit severely restricts horizontal advection of accumulated pollution plumes.",
        "color": "#F59E0B",
    },
    {
        "id": "factor-biomass",
        "name": "Thermal / Biomass Smoke Index",
        "category": "Satellite Fire Radiative Power",
        "value": "FRP 48.2 MW",
        "baseline": "FRP 10.0 MW",
        "contribution": 18.4,
        "impactType": "aggravator",
        "percentShare": 12.7,
        "description": "Upwind agricultural stubble pyrogenic emissions entering regional airshed.",
        "color": "#EAB308",
    },
    {
        "id": "factor-humidity",
        "name": "Relative Humidity",
        "category": "Meteorology",
        "value": "68%",
        "baseline": "45%",
        "contribution": 14.1,
        "impactType": "aggravator",
        "percentShare": 9.8,
        "description": "Elevated moisture enhances hygroscopic aerosol particle growth and nitrate partitioning.",
        "color": "#38BDF8",
    },
    {
        "id": "factor-temperature",
        "name": "Night Inversion Temperature",
        "category": "Thermal Gradient",
        "value": "31.4 °C",
        "baseline": "27.0 °C",
        "contribution": 8.2,
        "impactType": "aggravator",
        "percentShare": 5.7,
        "description": "Ground radiation cooling induces nocturnal temperature inversion trapping particulates.",
        "color": "#A855F7",
    },
    {
        "id": "factor-pbl",
        "name": "Planetary Boundary Layer Depth",
        "category": "Atmospheric Physics",
        "value": "420 m",
        "baseline": "1100 m",
        "contribution": -12.4,
        "impactType": "mitigator",
        "percentShare": 8.6,
        "description": "Residual afternoon mixing volume provides modest remaining air column dilution.",
        "color": "#10B981",
    },
]

XAI_EXPLANATION = {
    "title": "Why did the AI predict this AQI escalation?",
    "summary": "The predicted AQI surge from 287 to 342 is primarily driven by elevated tropospheric NO₂ (+42.5 pts) and an intense HCHO anomaly (+38.2 pts), compounded by stagnant nocturnal wind conditions (3.2 km/h) that prevent pollutant dispersion.",
    "modelDetails": {
        "architecture": "Dual-Branch Spatial-Temporal Hybrid: ConvLSTM-3D + Gradient Boosted Trees (XGBoost Ensemble)",
        "satelliteInputs": ["Sentinel-5P TROPOMI (HCHO L2, NO2 L2, UVAI)", "MODIS/VIIRS Fire Radiative Power (FRP)"],
        "groundInputs": ["CPCB CAAQMS Real-Time Sensor Telemetry (PM2.5, PM10, SO2, CO, O3)"],
        "meteorologicalInputs": ["ECMWF ERA5 / IMD GFS Weather Model (Wind Vectors, PBL, Temp, RH)"],
        "trainingDataset": "4.8 Million Geocoded Observation Vectors across 420 Indian Monitoring Stations (2021-2026)",
        "validationR2": "0.924 Test R² (RMSE: 14.8 AQI Index Points)",
    },
    "disclaimer": "Scientific Notice: AeroLens AI predictions and feature contributions represent statistical attribution models derived from satellite observations and meteorological physics. Anomaly detections identify spatial precursors and correlation patterns rather than judicial or legal culpability of specific entities.",
}

ALERTS_DATABASE: List[Dict[str, Any]] = [
    {
        "id": "alt-001",
        "severity": "Severe",
        "title": "High-severity HCHO anomaly detected in Delhi NCR",
        "location": "Delhi NCR (Anand Vihar - Jahangirpuri Sector)",
        "time": "15 mins ago (22:30 IST)",
        "timestamp": "2026-08-20T22:30:00+05:30",
        "category": "Satellite Anomaly",
        "description": "Sentinel-5P TROPOMI overpass detected a 185% surge in tropospheric formaldehyde (26.8 × 10¹⁵ molec/cm²) over baseline. AI model projects AQI crossing 340 by 04:00 AM.",
        "actionRequired": "Trigger Stage III Graded Response Action Plan (GRAP) advisory; inspect solvent storage units.",
        "acknowledged": False,
        "impactedPopulation": "18.4 Million",
    },
    {
        "id": "alt-002",
        "severity": "Severe",
        "title": "Rapid AQI deterioration predicted within the next 24 hours",
        "location": "Ludhiana - Khanna Agro-Industrial Corridor, Punjab",
        "time": "45 mins ago (22:00 IST)",
        "timestamp": "2026-08-20T22:00:00+05:30",
        "category": "Forecast Spike",
        "description": "Ensemble model forecasts AQI escalating from 264 to 318 due to thermal inversion and localized VOC oxidation downwind of industrial hubs.",
        "actionRequired": "Issue municipal air quality advisory for educational institutions and elderly residents.",
        "acknowledged": False,
        "impactedPopulation": "3.2 Million",
    },
    {
        "id": "alt-003",
        "severity": "Warning",
        "title": "Transboundary Aerosol & Ozone Precursor Accumulation",
        "location": "Patna - Hajipur Basin, Bihar",
        "time": "2 hours ago (20:45 IST)",
        "timestamp": "2026-08-20T20:45:00+05:30",
        "category": "Meteorology Alert",
        "description": "Valley wind stagnation (< 3.8 km/h) causing accumulation of particulate matter and chemical precursors across the Ganges river plain.",
        "actionRequired": "Intensify mechanical road sweeping and water misting along arterial corridors.",
        "acknowledged": True,
        "impactedPopulation": "4.8 Million",
    },
    {
        "id": "alt-004",
        "severity": "Warning",
        "title": "Elevated SO₂ & NO₂ Co-Plume Detected",
        "location": "Singrauli - Sonbhadra Energy Corridor, MP/UP",
        "time": "3 hours ago (19:30 IST)",
        "timestamp": "2026-08-20T19:30:00+05:30",
        "category": "Industrial Watch",
        "description": "Continuous Emission Monitoring Systems (CEMS) and TROPOMI column alignment shows secondary sulfate aerosol formation.",
        "actionRequired": "Automated notification dispatched to regional State Pollution Control Board.",
        "acknowledged": True,
        "impactedPopulation": "1.1 Million",
    },
    {
        "id": "alt-005",
        "severity": "Info",
        "title": "Sentinel-5P Orbit #38494 Data Ingestion Completed",
        "location": "National Coverage (India Airshed)",
        "time": "4 hours ago (18:30 IST)",
        "timestamp": "2026-08-20T18:30:00+05:30",
        "category": "Satellite Ingestion",
        "description": "Processed 12,480 geospatial pixels across Indian subcontinent with 94.2% cloud-free atmospheric penetration.",
        "actionRequired": "Spatial weights updated automatically in model inference pipeline.",
        "acknowledged": True,
        "impactedPopulation": "N/A",
    },
    {
        "id": "alt-006",
        "severity": "Info",
        "title": "CPCB CAAQMS 420-Station Real-Time Ground Sync Verified",
        "location": "National Ground Grid",
        "time": "5 hours ago (17:45 IST)",
        "timestamp": "2026-08-20T17:45:00+05:30",
        "category": "Ground Network",
        "description": "Hourly ground station calibration checks passed across all tier-1 and tier-2 monitoring nodes.",
        "actionRequired": "None (Nominal Operation)",
        "acknowledged": True,
        "impactedPopulation": "N/A",
    },
]

LOCATIONS_DATABASE: List[Dict[str, Any]] = [
    {"id": "delhi", "name": "Delhi NCR", "state": "Delhi", "aqi": 287, "status": "Poor", "lat": 28.6139, "lng": 77.2090, "hotspots": 3},
    {"id": "ludhiana", "name": "Ludhiana Corridor", "state": "Punjab", "aqi": 264, "status": "Poor", "lat": 30.9010, "lng": 75.8573, "hotspots": 2},
    {"id": "kanpur", "name": "Kanpur Cluster", "state": "Uttar Pradesh", "aqi": 238, "status": "Poor", "lat": 26.4499, "lng": 80.3319, "hotspots": 2},
    {"id": "patna", "name": "Patna Basin", "state": "Bihar", "aqi": 272, "status": "Poor", "lat": 25.5941, "lng": 85.1376, "hotspots": 2},
    {"id": "singrauli", "name": "Singrauli Belt", "state": "Madhya Pradesh", "aqi": 245, "status": "Poor", "lat": 24.1997, "lng": 82.6644, "hotspots": 1},
    {"id": "korba", "name": "Korba Basin", "state": "Chhattisgarh", "aqi": 224, "status": "Poor", "lat": 22.3595, "lng": 82.7501, "hotspots": 1},
    {"id": "mumbai", "name": "Mumbai MMR", "state": "Maharashtra", "aqi": 158, "status": "Moderate", "lat": 19.0760, "lng": 72.8777, "hotspots": 1},
    {"id": "kolkata", "name": "Kolkata Metro", "state": "West Bengal", "aqi": 172, "status": "Moderate", "lat": 22.5726, "lng": 88.3639, "hotspots": 1},
    {"id": "ahmedabad", "name": "Ahmedabad Vatva", "state": "Gujarat", "aqi": 215, "status": "Poor", "lat": 23.0225, "lng": 72.5714, "hotspots": 1},
    {"id": "hyderabad", "name": "Hyderabad Pharma", "state": "Telangana", "aqi": 134, "status": "Moderate", "lat": 17.3850, "lng": 78.4867, "hotspots": 1},
    {"id": "chennai", "name": "Chennai Manali", "state": "Tamil Nadu", "aqi": 112, "status": "Moderate", "lat": 13.0827, "lng": 80.2707, "hotspots": 0},
    {"id": "bengaluru", "name": "Bengaluru Tech", "state": "Karnataka", "aqi": 68, "status": "Satisfactory", "lat": 12.9716, "lng": 77.5946, "hotspots": 0},
]

ASSISTANT_KNOWLEDGEBASE: Dict[str, str] = {
    "why is pollution high in delhi": """**Delhi NCR Diagnostic Summary:**

Delhi NCR currently shows elevated pollution indicators (AQI 287, Poor) and a prominent **tropospheric HCHO anomaly of 26.8 × 10¹⁵ molec/cm² (+185% over baseline)** detected by Sentinel-5P TROPOMI. 

Key contributing mechanisms:
1. **Atmospheric Stagnation:** Low nocturnal surface wind speeds (3.2 km/h) restrict horizontal dispersion.
2. **Thermal Inversion:** A shallow Planetary Boundary Layer (~420m) compresses emissions near breathing level.
3. **Precursor Synergy:** Elevated NO₂ (78.4 µg/m³) from vehicular traffic reacting with volatile organic compounds (VOCs) accelerates secondary particulate formation.

*Note: This anomaly indicates intense localized photochemical oxidation and does not by itself prove a single judicial source.*""",

    "will aqi improve tomorrow": """**24-Hour Forecast Trajectory:**

Air quality is projected to **deteriorate further overnight**, peaking between **03:00 AM and 05:00 AM IST at AQI 342 (Very Poor)**.

**Improvement Outlook:**
- **Morning (08:00 AM - 11:00 AM):** Gradual dispersion begins as solar heating breaks the nocturnal inversion layer.
- **Afternoon (01:00 PM - 04:00 PM):** AQI is expected to improve to **242-252 (Poor)** as wind speeds increase to 8.5 km/h and boundary layer depth reaches ~1,090 meters.
- **Evening:** Moderate re-accumulation expected after 07:00 PM.""",

    "which area has the highest anomaly": """**Highest Detected Anomaly:**

**Delhi NCR (Anand Vihar - Jahangirpuri Belt)** currently records the highest HCHO anomaly in the national registry:
- **HCHO Column:** 26.8 × 10¹⁵ molec/cm² (+185% vs historical baseline).
- **Severity Rating:** **Severe Anomaly** (Confidence: 94.2%).

**Other High-Severity Anomaly Zones:**
1. **Ludhiana Corridor, Punjab:** +175% HCHO anomaly (Biomass pyrolysis + industrial VOCs).
2. **Patna Basin, Bihar:** +160% HCHO anomaly (Thermal inversion + transboundary basin inflow).
3. **Kanpur Cluster, UP:** +113% HCHO anomaly (Chemical tanning & secondary aerosols).""",

    "what factors influenced this prediction": """**Explainable AI (XAI) Attribution Breakdown:**

The predictive ensemble (ConvLSTM-XGBoost) attributes the current forecast primarily to:

1. **Tropospheric NO₂ Density (+42.5 AQI pts / 29.4% weight):** Highest positive driver accelerating aerosol formation.
2. **TROPOMI HCHO Anomaly (+38.2 AQI pts / 26.5% weight):** Surrogate tracer for reactive volatile organic compounds.
3. **Wind Stagnation (+29.0 AQI pts / 20.1% weight):** 3.2 km/h calm wind condition preventing advection.
4. **Thermal Inversion & Humidity (+22.3 AQI pts combined):** Moisture enhancing hygroscopic particle growth.
5. **Boundary Layer Dilution (-12.4 AQI pts):** Minor residual mixing mitigating extreme peaks.""",

    "what is hcho and why is it important for air quality": """**Formaldehyde (HCHO) as an Environmental Indicator:**

Formaldehyde (HCHO) is an intermediate product in the oxidation of almost all Volatile Organic Compounds (VOCs). 

**Why AeroLens AI tracks HCHO via Satellite:**
- **Short Atmospheric Lifetime (2-4 hours):** Because HCHO decays rapidly, satellite-detected HCHO column density serves as an excellent near-real-time spatial proxy for active VOC emissions and photochemical smog potential.
- **Precursor to Tropospheric Ozone & Secondary PM2.5:** High HCHO indicates a VOC-limited chemical regime where reducing organic vapor emissions is critical to arresting ozone spikes.
- **Early Warning:** Anomalies in HCHO frequently precede severe PM2.5 haze events by 6 to 18 hours.""",

    "how does aerolens ai combine satellite and ground data": """**Data Fusion Architecture:**

AeroLens AI utilizes a **Multi-Scale Spatial-Temporal Ensemble**:

1. **Satellite Remote Sensing (Top-Down):** Sentinel-5P TROPOMI provides high-resolution tropospheric column densities (HCHO, NO₂, Aerosol Index) covering areas without ground monitors.
2. **CPCB Ground Sensors (Bottom-Up):** 420 CAAQMS continuous monitoring stations provide calibrated surface-level microgram measurements of PM2.5, PM10, SO₂, and CO.
3. **Meteorological Assimilation:** High-resolution ECMWF ERA5 & IMD weather fields provide 3D wind velocity vectors, planetary boundary layer heights, and temperature gradients.
4. **AI Inference Engine:** A hybrid 3D-ConvLSTM + XGBoost model learns non-linear physical and chemical transport dynamics to produce 24h forecasts and anomaly alerts."""
}

def generate_chat_response(query: str) -> Dict[str, Any]:
    norm_query = query.lower().strip()
    
    for key, answer in ASSISTANT_KNOWLEDGEBASE.items():
        if key in norm_query or norm_query in key:
            return {
                "query": query,
                "response": answer,
                "model": "AeroLens-GeoEnsemble-FastAPI (v2.4)",
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "confidence": 0.94
            }
            
    default_resp = f"""**AeroLens AI Environmental Intelligence Analysis:**

Regarding your query: *"{query}"*

Our telemetry fusion engine correlates current Sentinel-5P TROPOMI satellite passes with 420 CPCB ground monitoring nodes across India. 

**Key Telemetry Snapshot:**
- **National Median AQI:** 287 (Poor) with localized severe spikes in the Indo-Gangetic Plain.
- **Active HCHO Anomalies:** 12 industrial/agricultural clusters identified with >50% elevation over seasonal baseline.
- **Meteorological Context:** Predominant northwesterly wind flow at low velocities (< 5 km/h) is causing valley stagnation across northern regions.

For specific location diagnostics, select an area on the **India Map** or view the **Hotspots** registry for granular sensor breakdowns."""

    return {
        "query": query,
        "response": default_resp,
        "model": "AeroLens-GeoEnsemble-FastAPI (v2.4)",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "confidence": 0.91
    }
